config/routes.rb
Rails.application.routes.draw do

  
  post 'events/upload_picture'

  resources :pictures

  resources :avatars, except: [:index, :show]
    post 'background_create' => 'avatars#background_create'
    patch 'background_update/:id' => 'avatars#background_update'

    post 'medium_ev_create' => 'avatars#medium_ev_create'
    patch 'medium_ev_update/:id' => 'avatars#medium_ev_update'

  resources :cities

  resources :states

  resources :friendships do
    member do
      post 'resolve'
    end
  end

  get 'autocomplete' => 'cities#autocomplete'

  post 'sent_invites' => 'plans#sent_invites'
  get 'invite' => 'plans#invite'
  post 'create_invite' => 'plans#create_invite'
  post 'user_answer' => 'plans#user_answer'
  resources :plans

  resources :categories

  resources :events do 
    resources :comments
  end

  get 'home/index'
  get '/about' => 'home#about', as: 'about'
  get '/contact' => 'home#contact', as: 'contact'
  get 'ownpage/:id' => 'users#own_user', as: 'ownpage'
  get 'users' => 'users#index'
  get 'profile' => 'users#profile'
  get 'user_friends/:id' => 'users#user_friends', as: 'user_friends'
  get 'user_info/:id' => 'users#user_info'
  get 'user_events/:id' => 'users#user_events', as: 'user_events'
  get 'user_photo/:id' => 'users#user_photo'
  get 'user_event' => 'users#user_event'
  get 'user_event_photo/:id' => 'users#user_event_photo'

    get 'user_modal' => 'users#open_modal', as: 'open_modal'
    get 'change_friend_tab/:id' => 'users#change_friend_tab', as: 'change_friend'
    get 'change_event_tab/:id' => 'users#change_event_tab', as: 'change_event'

  get 'friends' => 'users#friends', as: 'friends'

  devise_for :users

  root 'home#index'

  get 'filter' => 'events#filter'
  get 'filter_events' => 'events#filter_events'

end

app/models/state.rb
class State < ActiveRecord::Base
  has_many :cities
  has_many :events, through: :cities
  has_many :users, through: :cities
  translates :name
end

app/controllers/states_controller.rb
class StatesController < ApplicationController
  load_and_authorize_resource
  before_action :set_state, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @states = State.all
    respond_with(@states)
  end

  def show
    respond_with(@state)
  end

  def new
    @state = State.new
    respond_with(@state)
  end

  def edit
  end

  def create
    @state = State.new(state_params)
    @state.save
    respond_with(@state)
  end

  def update
    @state.update(state_params)
    respond_with(@state)
  end

  def destroy
    @state.destroy
    respond_with(@state)
  end

  private
    def set_state
      @state = State.find(params[:id])
    end

    def state_params
      params.require(:state).permit(:name)
    end
end

app/helpers/states_helper.rb
module StatesHelper
end

app/views/states/_form.html.slim
= form_for @state do |f|
  - if @state.errors.any?
    #error_explanation
      h2 = "#{pluralize(@state.errors.count, "error")} prohibited this state from being saved:"
      ul
        - @state.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .actions = f.submit

app/views/states/edit.html.slim
=I18n.locale
/= link_to 'Ru', "javascript:void(0);"
= link_to "Ru",  params.merge({:locale => :ru})
span |
= link_to "Ua",  params.merge({:locale => :uk})
span |
= link_to "En",   params.merge({:locale => :en})
h1 Editing state

== render 'form'

= link_to 'Show', @state
'|
= link_to 'Back', states_path

app/views/states/index.html.slim
=I18n.locale
/= link_to 'Ru', "javascript:void(0);"
= link_to "Ru",  params.merge({:locale => :ru})
span |
= link_to "Ua",  params.merge({:locale => :uk})
span |
= link_to "En",   params.merge({:locale => :en})
h1 Listing states

table
  thead
    tr
      th Name
      th
      th
      th

  tbody
    - @states.each do |state|
      tr
        td = state.name
        td = link_to 'Show', state
        td = link_to 'Edit', edit_state_path(state)
        td = link_to 'Destroy', state, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New State', new_state_path

app/views/states/new.html.slim
h1 New state

== render 'form'

= link_to 'Back', states_path

app/views/states/show.html.slim
p#notice = notice

p
  strong Name:
  = @state.name

= link_to 'Edit', edit_state_path(@state)
'|
= link_to 'Back', states_path