config/routes.rb
Rails.application.routes.draw do

  
  post 'events/upload_picture'

  resources :pictures

  resources :avatars, except: [:index, :show]
    post 'background_create' => 'avatars#background_create'
    patch 'background_update/:id' => 'avatars#background_update'

    post 'medium_ev_create' => 'avatars#medium_ev_create'
    patch 'medium_ev_update/:id' => 'avatars#medium_ev_update'

  resources :cities

  resources :states

  resources :friendships do
    member do
      post 'resolve'
    end
  end

  get 'autocomplete' => 'cities#autocomplete'

  post 'sent_invites' => 'plans#sent_invites'
  get 'invite' => 'plans#invite'
  post 'create_invite' => 'plans#create_invite'
  post 'user_answer' => 'plans#user_answer'
  resources :plans

  resources :categories

  resources :events do 
    resources :comments
  end

  get 'home/index'
  get '/about' => 'home#about', as: 'about'
  get '/contact' => 'home#contact', as: 'contact'
  get 'ownpage/:id' => 'users#own_user', as: 'ownpage'
  get 'users' => 'users#index'
  get 'profile' => 'users#profile'
  get 'user_friends/:id' => 'users#user_friends', as: 'user_friends'
  get 'user_info/:id' => 'users#user_info'
  get 'user_events/:id' => 'users#user_events', as: 'user_events'
  get 'user_photo/:id' => 'users#user_photo'
  get 'user_event' => 'users#user_event'
  get 'user_event_photo/:id' => 'users#user_event_photo'

    get 'user_modal' => 'users#open_modal', as: 'open_modal'
    get 'change_friend_tab/:id' => 'users#change_friend_tab', as: 'change_friend'
    get 'change_event_tab/:id' => 'users#change_event_tab', as: 'change_event'

  get 'friends' => 'users#friends', as: 'friends'

  devise_for :users

  root 'home#index'

  get 'filter' => 'events#filter'
  get 'filter_events' => 'events#filter_events'

end

app/models/city.rb
class City < ActiveRecord::Base
  translates :en_name
  belongs_to :state
  has_many :events
  has_many :users
end

app/models/event.rb
class Event < ActiveRecord::Base
  scope :name_filter, -> (name) { where("name like ?", "%#{name}%")}
  scope :adress_filter, -> (address) { where("adress like ?", "%#{address}%")}
  scope :description_filter, -> (description) { where("description like ?", "%#{description}%")}
  scope :data_filter, -> (data) { where("date(data) >= ?", "#{data.to_date}")}#{|event| event.data.to_date == data.to_date} }#where("data like ?", "%#{data}%")}
  scope :timeStart_filter, -> (timestart) { where("timeStart like ?", "#{timestart}")}


  belongs_to :user
  belongs_to :category
  belongs_to :city
  belongs_to :avatar, dependent: :destroy
  
  has_many :plans, :foreign_key => :measure_id, dependent: :destroy
  has_many :members, through: :plans, source: :member 

  has_many :relationships, -> { where("status like ?", 'come') }, :class_name => "Plan", :foreign_key => :measure_id
  has_many :participations, through: :relationships, source: :member

  has_many :all_relationships, -> { where("status like ? OR status like ?", 'come', 'invite') }, :class_name => "Plan", :foreign_key => :measure_id
  has_many :all_participations, through: :all_relationships, source: :member 

  has_many :invite_relationships, -> { where("status like ?", 'invite') }, :class_name => "Plan", :foreign_key => :measure_id
  has_many :invite_participations, through: :invite_relationships, source: :member 



  # Album has many photos
  has_many :pictures, :dependent => :destroy
  has_many :comments, :dependent => :destroy
  # enable nested attributes for photos through eventa class
  accepts_nested_attributes_for :pictures, allow_destroy: true



  validates_presence_of :name, :category_id, :description, :adress, :data, :timeStart, :endTime, :people_count#, :reg_type
  #validates :data , allow_blank: true, format: { with: /\d{2}\.\d{2}\.\d{4}/,
   # message: "only allows data dd.mm.yyyy" }
  #validates :timeStart, :endTime, allow_blank: true, format: { with: /\d{2}:\d{2}/,
   # message: "only allows time format hh:mm" }

  before_validation :ensure_than_city_for_event_exists

  geocoded_by :adress   # can also be an IP address
  after_validation :geocode          # auto-fetch coordinates


  def self.types_of_event
    [['Open event', 'open'], ['Close type', 'close']]
  end


  def self.counts_of_people
    [[I18n.t('events.little_group'), 'little'], [I18n.t('events.middle_group'), 'middle'], [I18n.t('events.great_group'), 'great']]
  end

  def self.replenishment
    [[I18n.t('events.manually'), 'manually'], [I18n.t('events.automatically'), 'automatically']]
  end

  def self.search(query)
    where("name like ?", "%#{query}%") 
  end

  def self.people_count_filter(count)
    where("people_count like ?", "%#{count}%")
  end

  def self.category_id_filter(category)
    where("category_id like ?", "%#{category}%")
  end

  def self.event_type_filter(type)
    where("event_type like ?", "%#{type}%")
  end

  def self.state_id_filter(state_id)
    State.find(state_id).events
    #where("state_id like ?", "%#{city_id}%")
  end

  def self.urban_filter(city_id)
    @city = City.where(en_name: city_id).first
    if @city.nil?
      where(event_type: 'none')
    else
      where(city_id: @city.id)
    end
    #where("state_id like ?", "%#{city_id}%")
  end

  def self.filter_by_data(start_date, end_date)
    if start_date.present?&&end_date.present?
       #binding.pry
      Event.select{|event| event.data.to_date >= start_date.to_date && event.data.to_date <= end_date.to_date}
    elsif start_date.present?
      Event.select{|event| event.data.to_date >= start_date.to_date}
    elsif end_date.present?
      Event.select{|event| event.data.to_date <= end_date.to_date}
    end
  end

  def self.filter_by_time(start_time, end_time)
    if start_time.present?&&end_time.present?
       #binding.pry
      Event.select{|event| event.timeStart.to_time >= start_time.to_time && event.timeStart.to_time <= end_time.to_time}
    elsif start_time.present?
      Event.select{|event| event.timeStart.to_time >= start_time.to_time}
    elsif end_time.present?
      Event.select{|event| event.timeStart.to_time <= end_time.to_time}
    end
  end

  def ensure_than_city_for_event_exists
    locale = I18n.locale 
    I18n.locale = :en
    I18n.locale = 'en'
    self.city_name = 'Ivano-Frankivsk' if self.city_name == 'Ivano-Frankivs\'k'
    self.city_name = 'Lviv' if self.city_name == 'L\'viv'
    self.city_name = 'Lutsk' if self.city_name == 'Luts\'k'
    self.city_name = 'Dnepropetrovsk' if self.city_name == 'Dnipropetrovs\'k'
    self.city_name = 'Zaporizhia' if self.city_name == 'Zaporizhzhia'
    self.city_name = 'Luhansk' if self.city_name == 'Luhans\'k'
    self.city_name = 'Odessa' if self.city_name == 'Odesa'
    self.city_name = 'Khmelnytskyi' if self.city_name == 'Khmel\'nyts\'kyi'
    self.city_name = 'Simferopol' if self.city_name == 'Simferopol\''
    unless City.where(en_name: self.city_name).exists?
      self.errors[:adress] << I18n.t('my_errors.messages.incorrect_city')
    else
      city = City.where(en_name: self.city_name).first
      self.city_id = city.id
    end
    I18n.locale = locale
  end

end

app/helpers/events_helper.rb
module EventsHelper
    def include_i18n_calendar_javascript
      content_for :head do
        javascript_include_tag case I18n.locale
          when :ru then "jquery.ui.datepicker-ru.js"
          when :uk then "jquery.ui.datepicker-uk.js"
          else raise ArgumentError, "Locale error"
        end
      end
    end

  def case_of_event(count)
    if count == 1
      t('case_of_event.one')
    elsif count<=4&&count>1
      t('case_of_event.few')
    elsif count>=5&&count<21
      t('case_of_event.many')
    elsif count>=21&&count%10 == 1
      t('case_of_event.one')
    elsif count>=22&&(count%10 == 2 || count%10 == 3 || count%10 == 4)
      t('case_of_event.few')    
    else
      t('case_of_event.many')
    end
  end

  def case_of_member(count)
    if count == 1
      t('case_of_member.one')
    elsif count<=4&&count>1
      t('case_of_member.few')
    elsif count>=5&&count<21
      t('case_of_member.many')
    elsif count>=21&&count%10 == 1
      t('case_of_member.one')
    elsif count>=22&&(count%10 == 2 || count%10 == 3 || count%10 == 4)
      t('case_of_member.few')    
    else
      t('case_of_member.many')
    end
  end

  def categories_collection
    Category.all.map {|c| ["#{c.title} #{Event.where(category_id: c.id).where('data >= ?', Date.today).count}", c.id]}
  end

  def number_format_people_count(event_id)
    @event = Event.find(event_id)
    if @event.people_count == 'little'
      return 15
    elsif @event.people_count == 'middle'
      return 25
    elsif @event.people_count == 'great'
      return 50
    else 
      return nil
    end
  end
    
  
  def confirm_ability(event)
    if user_signed_in?&& current_user.are_invited(event.id)
      return 'already_invited'
    elsif (user_signed_in?&&(event.event_type == 'open'||(event.event_type=='close'&&current_user.confirm_friend(event.user.id)))) && event.user != current_user
      return 'can'
    elsif (user_signed_in?&&(event.event_type == 'open'||(event.event_type=='close'&&!current_user.confirm_friend(event.user.id)))) && event.user != current_user
      return 'not_friend'
    elsif !user_signed_in?
      return 'not_user'
    end
  end

  def check_for_availability(event_id)
    @event = Event.find(event_id)
    if @event.reg_type == 'automatically'
      if (@event.people_count == 'little' && @event.participations.count <15)||(@event.people_count == 'middle' && @event.participations.count <50)||(@event.people_count == 'great' && @event.participations.count <100)
        return true 
      else
        return false 
      end
    elsif @event.reg_type == 'manually'
      if ((@event.people_count == 'little' && @event.participations.count <15)||(@event.people_count == 'middle' && @event.participations.count <50)||(@event.people_count == 'great' && @event.participations.count <100)) && @event.plans.where(status: 'turn').count < 1
        return true 
      else
        return false 
      end
    end
  end

  def user_check_for_availability(event_id)
    if (@event.people_count == 'little' && @event.participations.count <15)||(@event.people_count == 'middle' && @event.participations.count <50)||(@event.people_count == 'great' && @event.participations.count <100)
      return true 
    else
      return false 
    end
  end

  def category_icon(event_id)
    @event = Event.find(event_id)
    @cat = Category.find(@event.category_id)
    if  (@cat.title == 'семья-дети' || @cat.title == 'сім\'я-діти')      
      return "#{image_tag('family-children.png')}".html_safe    
    elsif (@cat.title == 'студенты' || @cat.title == 'студенти')      
      return "#{image_tag('student.png')}".html_safe
    elsif (@cat.title == 'работа' || @cat.title == 'робота')      
      return "#{image_tag('business.png')}".html_safe
    elsif  (@cat.title == 'домашние животные' || @cat.title == 'домашні улюбленці')      
      return "#{image_tag('pets.png')}".html_safe
    elsif (@cat.title == 'мови/наука' || @cat.title == 'языка/наука')      
      return "#{image_tag('languages-science.png')}".html_safe
    elsif  (@cat.title == 'технология' || @cat.title == 'технологія')      
      return "#{image_tag('technologies.png')}".html_safe
    elsif  (@cat.title == 'спорт' || @cat.title == 'спорт')      
      return "#{image_tag('sport.png')}".html_safe
    elsif  (@cat.title == 'искусство и ремесла' || @cat.title == 'мистецтво і ремесла')      
      return "#{image_tag('arts-crafts.png')}".html_safe
    elsif  (@cat.title == 'кулинария' || @cat.title == 'кулінарія')      
      return "#{image_tag('cooking.png')}".html_safe
    elsif  (@cat.title == 'рестораны' || @cat.title == 'ресторани')      
      return "#{image_tag('restaurants.png')}".html_safe
    elsif  (@cat.title == 'развлечения' || @cat.title == 'розваги')      
      return "#{image_tag('entertainment.png')}".html_safe
    elsif  (@cat.title == 'музыка' || @cat.title == 'музика')      
      return "#{image_tag('music.png')}".html_safe
    elsif  (@cat.title == 'bla-bla встречи (полемика)' || @cat.title == 'bla-bla зустрічі (полеміка)')      
      return "#{image_tag('bla-bla_meetings.png')}".html_safe
    elsif  (@cat.title == 'путешествия' || @cat.title == 'подорожі')      
      return "#{image_tag('travels.png')}".html_safe
    elsif  (@cat.title == 'для геймеров' || @cat.title == 'для геймерів')      
      return "#{image_tag('for_gamers.png')}".html_safe
    elsif  (@cat.title == 'культурный обмен' || @cat.title == 'культурний обмін')      
      return "#{image_tag('cultural_exchange.png')}".html_safe
    elsif  (@cat.title == 'авто/мотолюбители' || @cat.title == 'авто/мотолюбителі')      
      return "#{image_tag('auto/moto.png')}".html_safe
    else
      return nil
    end
  end

  def small_event_image(event_id)
    @event = Event.find(event_id)
    @cat = Category.find(@event.category_id)
    if  (@cat.title == 'семья-дети' || @cat.title == 'сім\'я-діти')      
      return "#{image_tag('default_family-children_event.png')}".html_safe    
    elsif (@cat.title == 'студенты' || @cat.title == 'студенти')      
      return "#{image_tag('default_student_event.png')}".html_safe
    elsif (@cat.title == 'работа' || @cat.title == 'робота')      
      return "#{image_tag('default_business_event.png')}".html_safe
    elsif  (@cat.title == 'домашние животные' || @cat.title == 'домашні улюбленці')      
      return "#{image_tag('default_pets_event.png')}".html_safe
    elsif (@cat.title == 'мови/наука' || @cat.title == 'языка/наука')      
      return "#{image_tag('default_languages-science_event.png')}".html_safe
    elsif  (@cat.title == 'технология' || @cat.title == 'технологія')      
      return "#{image_tag('default_technologies_event.png')}".html_safe
    elsif  (@cat.title == 'спорт' || @cat.title == 'спорт')      
      return "#{image_tag('default_sport_event.png')}".html_safe
    elsif  (@cat.title == 'искусство и ремесла' || @cat.title == 'мистецтво і ремесла')      
      return "#{image_tag('default_arts-crafts_event.png')}".html_safe
    elsif  (@cat.title == 'кулинария' || @cat.title == 'кулінарія')      
      return "#{image_tag('default_cooking_event.png')}".html_safe
    elsif  (@cat.title == 'рестораны' || @cat.title == 'ресторани')      
      return "#{image_tag('default_restaurants_event.png')}".html_safe
    elsif  (@cat.title == 'развлечения' || @cat.title == 'розваги')      
      return "#{image_tag('default_entertainment_event.png')}".html_safe
    elsif  (@cat.title == 'музыка' || @cat.title == 'музика')      
      return "#{image_tag('default_music_event.png')}".html_safe
    elsif  (@cat.title == 'bla-bla встречи (полемика)' || @cat.title == 'bla-bla зустрічі (полеміка)')      
      return "#{image_tag('default_bla-bla_meetings_event.png')}".html_safe
    elsif  (@cat.title == 'путешествия' || @cat.title == 'подорожі')      
      return "#{image_tag('default_travels_event.png')}".html_safe
    elsif  (@cat.title == 'для геймеров' || @cat.title == 'для геймерів')      
      return "#{image_tag('default_for_gamers_event.png')}".html_safe
    elsif  (@cat.title == 'культурный обмен' || @cat.title == 'культурний обмін')      
      return "#{image_tag('default_cultural_exchange_event.png')}".html_safe
    elsif  (@cat.title == 'авто/мотолюбители' || @cat.title == 'авто/мотолюбителі')      
      return "#{image_tag('default_auto/moto_event.png')}".html_safe
    end
  end

  def default_background_event(event_id)
    @event = Event.find(event_id)
    @cat = Category.find(@event.category_id)
    if  (@cat.title == 'семья-дети' || @cat.title == 'сім\'я-діти')      
      return "#{image_tag('default_background_family-children_event.jpg')}".html_safe    
    elsif (@cat.title == 'студенты' || @cat.title == 'студенти')      
      return "#{image_tag('default_background_student_event.jpg')}".html_safe
    elsif (@cat.title == 'работа' || @cat.title == 'робота')      
      return "#{image_tag('default_background_business_event.jpg')}".html_safe
    elsif  (@cat.title == 'домашние животные' || @cat.title == 'домашні улюбленці')      
      return "#{image_tag('default_background_pets_event.jpg')}".html_safe
    elsif (@cat.title == 'мови/наука' || @cat.title == 'языка/наука')      
      return "#{image_tag('default_background_languages-science_event.jpg')}".html_safe
    elsif  (@cat.title == 'технология' || @cat.title == 'технологія')      
      return "#{image_tag('default_background_technologies_event.jpg')}".html_safe
    elsif  (@cat.title == 'спорт' || @cat.title == 'спорт')      
      return "#{image_tag('default_background_sport_event_event.jpg')}".html_safe
    elsif  (@cat.title == 'искусство и ремесла' || @cat.title == 'мистецтво і ремесла')      
      return "#{image_tag('default_background_arts-crafts_event.jpg')}".html_safe
    elsif  (@cat.title == 'кулинария' || @cat.title == 'кулінарія')      
      return "#{image_tag('default_background_cooking_event.jpg')}".html_safe

app/views/events/_event1.html.slim
            .ev-list-item.ev-close
              = image_tag "ev-list-img.jpg"
              div class="ev-list-type ev-party"
              .ev-list-info
                h2 
                  = link_to 
                    = event.name
                h4 
                  | Час:
                  span = event.timeStart.strftime('%H:%M')
                  span = event.data.strftime('%d.%m.%Y')
                h4 
                  | Учасників:
                  span = event.participations.count
                h4.organizer
                  = image_tag "ev-list-user.jpg"
                  | Організатор:
                  span = User.find_by_id(event.user_id).last_name + ' ' + User.find_by_id(event.user_id).first_name



tr.event
  td
    - if @last_date.nil? || @last_date.to_date != event.data.to_date
      =event.data.to_date
tr.event
  td
    h1 = event.name
  td
    = User.find_by_id(event.user_id).last_name + ' ' + User.find_by_id(event.user_id).first_name
  td
    = event.participations.count
  td
    = number_format_people_count(event.id)
  td
    = event.timeStart.strftime('%H:%M')
  td
    = event.data.strftime('%d.%m.%Y')
  td
    = event.event_type

 
  - if can? :read, Event
    td
      = link_to 'Show', event
  - if can? :manage, Event
    td
      = link_to 'Edit', edit_event_path(event)
    td
      = link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' }

app/views/events/index_ajax.js.erb
$('#posts').html("<%= escape_javascript render('list_events') %>");
$('.pagination').html('<%= escape_javascript will_paginate(@events) %>');

app/views/events/new.html.erb
<h1>Нова подія</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/new1.html.erb
<h1>Нова подія</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.slim
.main-wrapper
  .content-wrapper.not-main
    = render "partials/header"
    .content.events.event-single
      .ev-img
        .ev-img-shadow
        - if @event.avatar && @event.avatar.avatar.file.exists? && @event.avatar.avatar_url(:large_image)
          = image_tag @event.avatar.avatar_url(:large_image)
        -else
          = default_background_event(@event.id)
      .row
        .ev-title
          .come-to-ev
            - if current_user && (current_user.id == @event.user.id)
              .ev-manage
                = link_to I18n.t('event.control'), "javascript:void(0);", class:"btn-5"
                .ev-menage-show
                  = link_to I18n.t('event.del_event'), event_path(@event), :method => :delete, :data => { :confirm => I18n.t('event.destroy_event') }, class:"btn-4"
                  |  
                  = link_to I18n.t('event.edit_event'), edit_event_path(@event), class:"btn-4"

            - if confirm_ability(@event) == 'can'
              = simple_form_for @plan do |f|
                = f.hidden_field :measure_id,  value: @event.id
                - if current_user.come(@plan.measure_id)
                  = button_to I18n.t('event.btn_dont_go'), plan_path(@plan), name: 'do_not_go', :method => :delete, :class => "btn-5"
                - elsif current_user.in_turn(@event.id)
                  =I18n.t('event.you_are_in_turn') 
                  = button_to I18n.t('event.btn_uncoming_turn'), plan_path(@plan), name: 'do_not_go_turn', :method => :delete, :class => "btn-5"
                - elsif !current_user.come(@plan.measure_id)
                  - if check_for_availability(@event.id)
                    = f.submit I18n.t('event.reg_at'), name: 'come', :class => "btn-5"
                  - else
                    =I18n.t('event.places_occupied')
                    = f.submit I18n.t('event.btn_turn'), name: 'turn'
            - elsif confirm_ability(@event) == 'not_friend'
              p = I18n.t('event.you_are_not_friend')
            - elsif confirm_ability(@event) == 'not_user'
              p =I18n.t('event.sing_in_up')
            - elsif confirm_ability(@event) == 'already_invited'
              p =I18n.t('event.already_invited')
              = link_to I18n.t('event.btn_my_events'), user_events_path(current_user.id)
          h1 = @event.name
          p.ev-start
            =t('header.begin')
            |:  
            = I18n.l @event.timeStart, :format => :single_event
            |, 
            = I18n.l @event.data.to_date, :format => :single_event
      .row.ev-single-info
        .medium-4.small-12.columns.ev-single-main-info
          .ev-category.ev-list-type.ev-party
            = category_icon(@event.id)
            = Category.find_by_id(@event.category_id).title
            / = form_for @event, :html => {:multipart => true}, :method => 'post', url: {:controller => 'events', :action => 'upload_picture'} do |f|
            /   = hidden_field_tag :id, @event.id
            /   = file_field_tag "pictures[]", type: :file, multiple: true
            /   = hidden_field_tag(:picture, 'picture')
            /   = f.submit I18n.t("event.save")
          .ev-address
            - if @event.street_name?
              span[id = "st_name"]
            - else 
              span[id = "st_name" class = "hide"]
            - if @event.street_number?
              span[id = "st_num"]
            - else 
              span[id = "st_num" class = "hide"]
            = city_name(@event.id)
            /= @event.city_name
          h4.organizer
            = link_to(small_avatar(@event.user.id), {:action => "own_user", :controller => "users", :id => @event.user.id})
              /= image_tag @event.user.avatar.avatar_url(:small)
            =t('events.organizer')
            span  = link_to(@event.user.first_name + " " + @event.user.last_name, {:action => "own_user", :controller => "users", :id => @event.user.id})
          .ev-members
            | 
            =I18n.t('events.members')
            span  
              = @event.participations.count
              | /
              = number_format_people_count(@event.id)
            .ev-members-items
              -@event.participations[0..17].each do |u|
                = link_to 'javascript:void(0);' do
                  = link_to(small_avatar(u.id), {:action => "own_user", :controller => "users", :id => u.id})

            - if @event.participations.length > 18
              - count = @event.participations.length - 18
              = link_to "#{I18n.t('event.more_members')} #{count} #{case_of_member(count)}", event_path(id: @event.id, status: 'more_members'), remote: true, class: 'other_member'
            /
              - if @event.invite_participations.count > 0
                | Запрошених користувачів  
                = @event.invite_participations.count

        .medium-8.small-12.columns
          .ev-single-descr-info
            .ev-description
              p = @event.description
            .map-wr
              script[src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry&language=#{I18n.locale.to_s}" type="text/javascript"]
              script[src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js" type="text/javascript"]
              div[style="width: 100%;"]
                #map[style="width: 100%; height: 300px;"]
              - content_for :scripts do
                script
                  |  handler = Gmaps.build('Google'); handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){ markers = handler.addMarkers(#{raw @hash.to_json}); handler.bounds.extendWith(markers); handler.fitMapToBounds(); handler.getMap().setZoom(17);}); 
                  |      var findResult = function(results, name){ var result =  _.find(results, function(obj){ return obj.types[0] == name && obj.types[1] == "political"; }); return result ? result.short_name : null;  };

                  | function getAddress(){ var latlng = new google.maps.LatLng(#{@event.latitude}, #{@event.longitude});  geocoder = new google.maps.Geocoder();  geocoder.geocode({'latLng': latlng}, function(results, status) { if (status == google.maps.GeocoderStatus.OK) { results = results[0].address_components;   var city = findResult(results, "locality");  var route = results[0].short_name; var street = results[1].short_name; $('#st_num').html(route + ", "); $('#st_name').html(street + " ");} }); };
                  | getAddress();

            - if !current_user.nil? && current_user.id == @event.user_id
              = form_for @event, :html => {:multipart => true}, :method => 'post', url: {:controller => 'events', :action => 'upload_picture'} do |f|
                .ph-drag-drop
                  p
                    =I18n.t('event.drag_image')
                  p
                    =t('event.or_push_button')
                    = link_to I18n.t('event.btn_download'), "javascript:void(0);", class: "btn-4" 
                  = hidden_field_tag :id, @event.id
                  = file_field_tag "pictures[]", type: :file, multiple: true, class: 'picturesPre pictures1'
                  = hidden_field_tag(:picture, 'picture')
                .preview-area.with-scroll
                = f.submit I18n.t("event.save"), class: "btn-5"
            -if @event.pictures.count > 0
              .ev-single-descr-info.ev-photos
                .date
                  /| 18 травня 2012
                h2
                  = I18n.t('event.photo_report')
                .with-scroll
                  /-count_picture = 0 
                  - @event.pictures.each do |p|
                    .ev-ph-item
                      a href="#{p.picture_url(:large_picture) }" data-lightbox="image-1" data-title="My caption"
                        = image_tag p.picture_url(:medium_picture)
                        - if !current_user.nil? && current_user.id == @event.user_id
                          = link_to 'X', picture_path(p.id), class: "del-img", :method => :delete, :data => { :confirm => I18n.t('event.destroy_photo') }

          .comments-wr
            - if current_user && (@event.event_type == 'open' || ( @event.event_type == 'close' && @event.user.confirm_friend(current_user.id) ) || current_user.id == @event.user.id )
              = simple_form_for([@event, @event.comments.build], remote: true, html: {class: 'send-comment'}) do |f| 
                = f.text_area :body, :placeholder => I18n.t('event.write_comment'), required: true
                = f.submit I18n.t('event.btn_send'), class:"btn-6"
                = button_tag I18n.t('event.btn_cansel'), type: :reset, class: "btn-7"
            - elsif current_user && ( @event.event_type == 'close' && !@event.user.confirm_friend(current_user.id)  && current_user.id != @event.user.id )
              .comment-access
                p = I18n.t('event.only_friends')
            - else
              .comment-access
                p = I18n.t('event.only_reg_users')
                = link_to t('sessions.registration'), new_user_registration_path
                span
                  | |
                = link_to t('header.enter'), new_user_session_path
            .comments_block
              -@event.comments.reverse_each do |comment| 
                - next if comment.new_record?
                = render 'events/comments/comment', comment: comment


    = render "partials/footer"