config/routes.rb
Rails.application.routes.draw do

  
  post 'events/upload_picture'

  resources :pictures

  resources :avatars, except: [:index, :show]
    post 'background_create' => 'avatars#background_create'
    patch 'background_update/:id' => 'avatars#background_update'

    post 'medium_ev_create' => 'avatars#medium_ev_create'
    patch 'medium_ev_update/:id' => 'avatars#medium_ev_update'

  resources :cities

  resources :states

  resources :friendships do
    member do
      post 'resolve'
    end
  end

  get 'autocomplete' => 'cities#autocomplete'

  post 'sent_invites' => 'plans#sent_invites'
  get 'invite' => 'plans#invite'
  post 'create_invite' => 'plans#create_invite'
  post 'user_answer' => 'plans#user_answer'
  resources :plans

  resources :categories

  resources :events do 
    resources :comments
  end

  get 'home/index'
  get '/about' => 'home#about', as: 'about'
  get '/contact' => 'home#contact', as: 'contact'
  get 'ownpage/:id' => 'users#own_user', as: 'ownpage'
  get 'users' => 'users#index'
  get 'profile' => 'users#profile'
  get 'user_friends/:id' => 'users#user_friends', as: 'user_friends'
  get 'user_info/:id' => 'users#user_info'
  get 'user_events/:id' => 'users#user_events', as: 'user_events'
  get 'user_photo/:id' => 'users#user_photo'
  get 'user_event' => 'users#user_event'
  get 'user_event_photo/:id' => 'users#user_event_photo'

    get 'user_modal' => 'users#open_modal', as: 'open_modal'
    get 'change_friend_tab/:id' => 'users#change_friend_tab', as: 'change_friend'
    get 'change_event_tab/:id' => 'users#change_event_tab', as: 'change_event'

  get 'friends' => 'users#friends', as: 'friends'

  devise_for :users

  root 'home#index'

  get 'filter' => 'events#filter'
  get 'filter_events' => 'events#filter_events'

end

app/models/plan.rb
class Plan < ActiveRecord::Base
  belongs_to :member,  :class_name => "User" 
  belongs_to :measure, :class_name => "Event" 
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :set_plan, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @plans = Plan.all
    respond_with(@plans)
  end

  def show
    respond_with(@plan)
  end

  def new
    @plan = Plan.new
    respond_with(@plan)
  end

  def edit
  end

  def create
    @event = Event.find(plan_params[:measure_id])
    @plan = Plan.new(plan_params)
    @plan.member_id = current_user.id
    if params[:come]
      @plan.status = 'come'
    elsif params[:turn]
      @plan.status = 'turn'
      @plan.turn_number = 1
      @plan.turn_number = Plan.where(status: 'turn', measure_id: @event.id).maximum(:turn_number) + 1 if Plan.where(status: 'turn', measure_id: @event.id).exists?
    end
    @plan.save
    redirect_to @event
  end

  def invite 
    @user = User.find(params[:user_id]) if params[:user_id]
    @event = Event.find(params[:event_id]) if params[:event_id]
  end

  def create_invite 
    @event = Event.find(params[:event_id])
    @plan = Plan.create(measure_id: params[:event_id], member_id: params[:user_id], status: 'invite')
    render text: "#{@plan.measure_id} #{@plan.member_id} #{@plan.measure.name} #{@plan.status}"
  end

  def user_answer
    @plan = Plan.find(params[:plan_id])
    @plan.status = 'come' if params[:answer] == 'come'
    @plan.status = 'decline' if params[:answer] == 'decline'
    @event = @plan.measure
    if params[:answer] == 'turn'
      @plan.status = 'turn'
      @plan.turn_number = 1
      @plan.turn_number = Plan.where(status: 'turn', measure_id: @event.id).maximum(:turn_number) + 1 if Plan.where(status: 'turn', measure_id: @event.id).exists?
    end
    @plan.save
    respond_to do |format|
      format.html {}
      format.js   {render 'users/user_answer.js.erb'}
    end  
  end

  def sent_invites
    @event = Event.find_by("id = ?",params[:event_id])
    @users = User.find(params[:user_ids])
    @users.each do |u|
      if u.plans.where(measure_id: @event.id, status: 'turn').exists?
        @plan = u.plans.where(measure_id: @event.id, status: 'turn').first
        @plan.status = 'come'
        @plan.turn_number = nil
        @plan.save
      else
        u.plans.create(measure_id: @event.id, status: 'invite')
      end
    end
    #binding.pry
  end

  def update
    @event = Event.find(plan_params[:measure_id])
    @plan.update(plan_params)
    if params[:come]
      @plan.status = 'come'
     elsif params[:turn]
      @plan.status = 'turn'
      @plan.turn_number = Plan.where(status: 'turn',measure_id: @event.id).maximum(:turn_number) + 1
    end
    @plan.save
    redirect_to @event
  end

  def destroy
    @event =  Event.find(plan_params[:measure_id])
    if params[:do_not_go] && @event.plans.where(status: 'turn').exists? && @event.reg_type == 'automatically'
      turn_number = @event.plans.where(status: 'turn').minimum(:turn_number)
      @turn_plan = @event.plans.where(status: 'turn').where(turn_number: turn_number).first
      @turn_plan.status = 'come'
      @turn_plan.turn_number = nil
      @turn_plan.save
    end
    @plan.destroy
    #@plan.destroy
    respond_with(@event)
  end

  private
    def set_plan
      @plan = Plan.find(params[:id])
    end

    def plan_params
      params.require(:plan).permit(:status, :measure_id)
    end
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/plans/_form.html.erb
<%= form_for(@plan) do |f| %>
  <% if @plan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@plan.errors.count, "error") %> prohibited this plan from being saved:</h2>

      <ul>
      <% @plan.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/plans/edit.html.erb
<h1>Editing plan</h1>

<%= render 'form' %>

<%= link_to 'Show', @plan %> |
<%= link_to 'Back', plans_path %>

app/views/plans/index.html.erb
<h1>Listing plans</h1>

<table>
  <thead>
    <tr>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @plans.each do |plan| %>
      <tr>
        <td><%= plan.status %></td>
        <td><%= link_to 'Show', plan %></td>
        <td><%= link_to 'Edit', edit_plan_path(plan) %></td>
        <td><%= link_to 'Destroy', plan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Plan', new_plan_path %>

app/views/plans/invite.html.haml
-if @user
  %p Invite #{@user.first_name} to 
  - if Event.exists?
    %table
      %thead
        %tr
          %th Event name
          %th{:colspan => "3"}
      - if flash[:alert]
        .notice= flash[:alert]
      %tbody
        - current_user.events.each do |event|
          %tr
            %td= event.name     |
            %td= link_to 'Invite to event', create_invite_path(user_id: @user.id, event_id: event.id), method: 'post'
            -# if can? :read, Event
              %td= link_to 'Show', create_invite_path(user_id: @user.id, event_id: event.id)
            -# if can? :manage, Event
              %td= link_to 'Edit', edit_event_path(event)
              %td= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' }
  - else
    %p You don't have any event
-elsif @event
  .users
    %h2 Friends
    %ul
      -for friendship in current_user.user_friendships
        %li
          - if friendship.user == current_user
            =h friendship.friend.first_name
            = link_to 'Invite to event', create_invite_path(user_id: friendship.friend.id, event_id: @event.id), method: 'post'
          - else 
            =h friendship.user.first_name
            = link_to 'Invite to event', create_invite_path(user_id: friendship.user.id, event_id: @event.id), method: 'post'

app/views/plans/new.html.erb
<h1>New plan</h1>

<%= render 'form' %>

<%= link_to 'Back', plans_path %>

app/views/plans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Status:</strong>
  <%= @plan.status %>
</p>

<%= link_to 'Edit', edit_plan_path(@plan) %> |
<%= link_to 'Back', plans_path %>